version: '3'
services:
    weedu-client:
      container_name: weedu-client
      restart: always
      environment:
        - REACT_APP_EMCASH_API_URL=http://localhost
        - REACT_APP_BATCH_TRANSFER_SHEET_MODEL_URL=https://emcashpub.s3.us-east-2.amazonaws.com/lote-c55352c5-2970-408f-bbe0-3d7fba373866.xlsx
      build:
          context: .
          dockerfile: Dockerfile
      ports:
        - "3001:3000"
      deploy:
        resources:
          limits:
            memory: 768M
          reservations:
            memory: 512M

